<<<<<<< HEAD
#remotes::install_github('jaburgoyne/compmus')

library(tidyverse)
library(spotifyr)
library(compmus)


# code is per track
sunny <-
  get_tidy_audio_analysis("4vju55Ag7apDL2CfotuE7Q") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)


sunny %>%
  mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()

---
  title: "Portfolio"
author: "Coen van den Elsen"
data: "DATA"
output: 
  flexdashboard::flex_dashboard:
  storyboard: true
orientation: columns
vertical_layout: fill
theme:
  version: 4
bootswatch: solar
self_contained: false
---
  
  ```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(spotifyr)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(viridis)
library(viridisLite)
library(forcats)
library(compmus)
```


```{r data load generating_summary_statistics, echo = FALSE}

fkj <- get_playlist_audio_features("", "37i9dQZF1DZ06evO1x7AE9")
tom_misch <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0P3UNG")
lianne_de_havas <- get_playlist_audio_features("", "37i9dQZF1DZ06evO1EwgdW")
joy_crookes <- get_playlist_audio_features("", "37i9dQZF1DZ06evO3w1CV3")
jorja_smith <- get_playlist_audio_features("", "37i9dQZF1DX1ykpeqTwA5m")
mahalia <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0AHQ3T")

erykah_badu <- get_playlist_audio_features("", "37i9dQZF1DZ06evO4zhZAI")
steve_wonder <- get_playlist_audio_features("", "37i9dQZF1DZ06evO4iAGsg")
bill_withers <- get_playlist_audio_features("", "37i9dQZF1DX5MwHlrzAPLQ")
marvin_gaye <- get_playlist_audio_features("", "37i9dQZF1DZ06evO1VI5MY")
ray_charles <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0FPX4A")
aretha_franklin <- get_playlist_audio_features("", "37i9dQZF1DZ06evO4mP172")

```


```{r data prep, echo = FALSE}
new <- rbind(fkj,tom_misch,lianne_de_havas,jorja_smith,mahalia,joy_crookes)
new <- new %>%
  add_column(generation = "new")

old <- rbind(erykah_badu,steve_wonder,bill_withers,marvin_gaye,ray_charles,aretha_franklin)
old <- old %>%
  add_column(generation = "old")

all <- rbind(old, new)

```  

```{r defining_a_theme, echo = FALSE}
# Better to define your own function than to always type the same stuff
theme_ilo <- function(){
  theme_minimal() +
    theme(
      text = element_text(color = "gray25"),
      plot.subtitle = element_text(size = 12),
      plot.caption = element_text(color = "gray30"),
      plot.background = element_rect(fill = "gray95"),
      plot.margin = unit(c(5, 10, 5, 10), units = "mm")
    )
}
```  


### Corpus motivation

I want to research soul music. I am a musician myself and make soul/jazz/funk/RnB, I am curious how the music I listen and make everyday came to be and differce from earlier Thats why I decided to see how big soul artists through the years compare to eachother. To decide what artists I should include, I made a mix of artists that inspire me, artists that have ment a lot for the genre in the persprective of my guitar teacher (jazz conservatory master) and artists that made the top on online websites (TO BE INCORPORATED LATER https://www.rollingstone.com/music/music-lists/rolling-stone-readers-pick-the-top-10-rb-soul-singers-of-all-time-16607/. These are the artists per generation:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Old Generation: Erykah Badu, Steve Wonder, Bill Withers, Marvin Gaye, Ray charles, Aretha Franklin.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         new generation: Tom Misch, Lianne De Havas, FKJ, Joy Crookes, Jorja Smith, Mahalia.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         I, and the sources mentioned above, think these artists really represent the genre in their time and think it is a good representation of what I want to research. I do think more names could be added, such as Bobby Hebbs, but I don’t think this would be of use. I suspect the most difference will be seen in tempo and time, as most songs have been going faster and getting shorter through the years The tracks of all these artists will be compared, I think Bill Withers is the most atypical, because he does a lot of genres besides soul alone (like blues etc.)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ### Visualizations part 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```{r fig.height = 6, fig.width = 8, fig.align = "center", warning=FALSE,  echo = FALSE}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(new, aes(x=tempo , y= playlist_name, size = valence, color = playlist_name)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point() + scale_fill_viridis_d() + xlim(0,250) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "New Generation", subtitle = "Valence and tempo per artist playlist", colour = "Playlist name",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Tempo", y = "Playlist name", size = "Valence") + theme_tufte() + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(old, aes(x=tempo , y= playlist_name, size = valence, color = playlist_name)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point() + scale_fill_viridis_d()  + xlim(0,250) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "Old Generation", subtitle = "Valence and tempo per artist playlist", colour = "Playlist name",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Tempo", y = "Playlist name", size = "Valence") + theme_tufte() + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         *** 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Interesting observations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         What is interesting to see is that there is 1 outlier, a song of Erykah Badu. This one is called "Hi", which is not a full song, but definitaly music, it is in the "This is Erykah Badu" playlist. This song has no data, valence and tempo are set to 0. Another interesting point is that 1 song of Bill Withers, Dont want you on my mind, has a very high tempo (240-250). There also was an oultier like "Hi" in the This is Mahalia playlist, but spotify took that one out during the time I was working on this assignment.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ### Visualizations part 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```{r fig.height = 6, fig.width = 8, fig.align = "center", warning=FALSE,  echo = FALSE}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(all, aes(x=energy , y= danceability, color = generation)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point() + scale_fill_viridis_d() + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "Both Generations", subtitle = "energy and danceability per generation", colour = "Generation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Energy", y = "Danceability",) + theme_tufte() + facet_grid( facets = . ~ generation) + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(all, aes(x=valence , y= tempo, color = generation)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point(size = 3) + scale_fill_viridis_d() + ylim(45,250)+ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "Both Generations", subtitle = "Valence and tempo per generation", colour = "Generation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Valence", y = "Tempo") + theme_tufte() + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         *** 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           TEXT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ### chromogram of soul track
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```{r fig.height = 6, fig.width = 8, fig.align = "center", warning=FALSE,  echo = FALSE}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sunny <-
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           get_tidy_audio_analysis("4vju55Ag7apDL2CfotuE7Q") %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           select(segments) %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           unnest(segments) %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           select(start, duration, pitches)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sunny %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           compmus_gather_chroma() %>% 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ggplot(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             aes(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               x = start + duration / 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               width = duration,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               y = pitch_class,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               fill = value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_tile() +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           theme_minimal() +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           scale_fill_viridis_c()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ***
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           text explaining why
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         starts eminor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
=======
#remotes::install_github('jaburgoyne/compmus')

library(tidyverse)
library(spotifyr)
library(compmus)


# code is per track
sunny <-
  get_tidy_audio_analysis("4vju55Ag7apDL2CfotuE7Q") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)


sunny %>%
  mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()

---
  title: "Portfolio"
author: "Coen van den Elsen"
data: "DATA"
output: 
  flexdashboard::flex_dashboard:
  storyboard: true
orientation: columns
vertical_layout: fill
theme:
  version: 4
bootswatch: solar
self_contained: false
---
  
  ```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(spotifyr)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(viridis)
library(viridisLite)
library(forcats)
library(compmus)
```


```{r data load generating_summary_statistics, echo = FALSE}

fkj <- get_playlist_audio_features("", "37i9dQZF1DZ06evO1x7AE9")
tom_misch <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0P3UNG")
lianne_de_havas <- get_playlist_audio_features("", "37i9dQZF1DZ06evO1EwgdW")
joy_crookes <- get_playlist_audio_features("", "37i9dQZF1DZ06evO3w1CV3")
jorja_smith <- get_playlist_audio_features("", "37i9dQZF1DX1ykpeqTwA5m")
mahalia <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0AHQ3T")

erykah_badu <- get_playlist_audio_features("", "37i9dQZF1DZ06evO4zhZAI")
steve_wonder <- get_playlist_audio_features("", "37i9dQZF1DZ06evO4iAGsg")
bill_withers <- get_playlist_audio_features("", "37i9dQZF1DX5MwHlrzAPLQ")
marvin_gaye <- get_playlist_audio_features("", "37i9dQZF1DZ06evO1VI5MY")
ray_charles <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0FPX4A")
aretha_franklin <- get_playlist_audio_features("", "37i9dQZF1DZ06evO4mP172")

```


```{r data prep, echo = FALSE}
new <- rbind(fkj,tom_misch,lianne_de_havas,jorja_smith,mahalia,joy_crookes)
new <- new %>%
  add_column(generation = "new")

old <- rbind(erykah_badu,steve_wonder,bill_withers,marvin_gaye,ray_charles,aretha_franklin)
old <- old %>%
  add_column(generation = "old")

all <- rbind(old, new)

```  

```{r defining_a_theme, echo = FALSE}
# Better to define your own function than to always type the same stuff
theme_ilo <- function(){
  theme_minimal() +
    theme(
      text = element_text(color = "gray25"),
      plot.subtitle = element_text(size = 12),
      plot.caption = element_text(color = "gray30"),
      plot.background = element_rect(fill = "gray95"),
      plot.margin = unit(c(5, 10, 5, 10), units = "mm")
    )
}
```  


### Corpus motivation

I want to research soul music. I am a musician myself and make soul/jazz/funk/RnB, I am curious how the music I listen and make everyday came to be and differce from earlier Thats why I decided to see how big soul artists through the years compare to eachother. To decide what artists I should include, I made a mix of artists that inspire me, artists that have ment a lot for the genre in the persprective of my guitar teacher (jazz conservatory master) and artists that made the top on online websites (TO BE INCORPORATED LATER https://www.rollingstone.com/music/music-lists/rolling-stone-readers-pick-the-top-10-rb-soul-singers-of-all-time-16607/. These are the artists per generation:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Old Generation: Erykah Badu, Steve Wonder, Bill Withers, Marvin Gaye, Ray charles, Aretha Franklin.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         new generation: Tom Misch, Lianne De Havas, FKJ, Joy Crookes, Jorja Smith, Mahalia.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         I, and the sources mentioned above, think these artists really represent the genre in their time and think it is a good representation of what I want to research. I do think more names could be added, such as Bobby Hebbs, but I don’t think this would be of use. I suspect the most difference will be seen in tempo and time, as most songs have been going faster and getting shorter through the years The tracks of all these artists will be compared, I think Bill Withers is the most atypical, because he does a lot of genres besides soul alone (like blues etc.)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ### Visualizations part 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```{r fig.height = 6, fig.width = 8, fig.align = "center", warning=FALSE,  echo = FALSE}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(new, aes(x=tempo , y= playlist_name, size = valence, color = playlist_name)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point() + scale_fill_viridis_d() + xlim(0,250) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "New Generation", subtitle = "Valence and tempo per artist playlist", colour = "Playlist name",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Tempo", y = "Playlist name", size = "Valence") + theme_tufte() + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(old, aes(x=tempo , y= playlist_name, size = valence, color = playlist_name)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point() + scale_fill_viridis_d()  + xlim(0,250) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "Old Generation", subtitle = "Valence and tempo per artist playlist", colour = "Playlist name",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Tempo", y = "Playlist name", size = "Valence") + theme_tufte() + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         *** 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Interesting observations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         What is interesting to see is that there is 1 outlier, a song of Erykah Badu. This one is called "Hi", which is not a full song, but definitaly music, it is in the "This is Erykah Badu" playlist. This song has no data, valence and tempo are set to 0. Another interesting point is that 1 song of Bill Withers, Dont want you on my mind, has a very high tempo (240-250). There also was an oultier like "Hi" in the This is Mahalia playlist, but spotify took that one out during the time I was working on this assignment.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ### Visualizations part 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```{r fig.height = 6, fig.width = 8, fig.align = "center", warning=FALSE,  echo = FALSE}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(all, aes(x=energy , y= danceability, color = generation)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point() + scale_fill_viridis_d() + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "Both Generations", subtitle = "energy and danceability per generation", colour = "Generation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Energy", y = "Danceability",) + theme_tufte() + facet_grid( facets = . ~ generation) + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ggplot(all, aes(x=valence , y= tempo, color = generation)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_point(size = 3) + scale_fill_viridis_d() + ylim(45,250)+ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(title = "Both Generations", subtitle = "Valence and tempo per generation", colour = "Generation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x = "Valence", y = "Tempo") + theme_tufte() + theme_ilo()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         *** 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           TEXT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ### chromogram of soul track
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```{r fig.height = 6, fig.width = 8, fig.align = "center", warning=FALSE,  echo = FALSE}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sunny <-
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           get_tidy_audio_analysis("4vju55Ag7apDL2CfotuE7Q") %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           select(segments) %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           unnest(segments) %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           select(start, duration, pitches)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sunny %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           compmus_gather_chroma() %>% 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ggplot(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             aes(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               x = start + duration / 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               width = duration,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               y = pitch_class,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               fill = value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           geom_tile() +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           theme_minimal() +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           scale_fill_viridis_c()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ***
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           text explaining why
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         starts eminor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
>>>>>>> de0a7202628668b395909fc3975298ba8d7c03fd
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         